version: "3"

services:

  whaleyeah:
    image: python:3.12
    restart: always
    ports:
      - "127.0.0.1:10000:10000"
    networks:
      - whaleyeah-network
    volumes:
      - ./whaleyeah:/whaleyeah
      - ./bot.py:/bot.py
      - ./database:/data/db
      - ./entrypoint.sh:/entrypoint.sh
      - ./etc/config.json:/config.json
      - ./requirements.txt:/requirements.txt
      - whaleyeah-tmp:/tmp
      - whaleyeah-sitepackages:/usr/local/lib/python3.12/site-packages

    working_dir: /
    command: python bot.py -c /config.json
    entrypoint: /entrypoint.sh
    depends_on:
      - whaleyeah-mongodb
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"

  whaleyeah-mongodb:
    image: mongodb/mongodb-community-server:latest
    user: $MYUID:$MYGID
    restart: always
    command: mongod --config /etc/mongod.conf
    volumes:
      - ./etc/mongod.conf:/etc/mongod.conf
      - ./database:/data/db
      - whaleyeah-tmp:/tmp
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"

volumes:
  whaleyeah-tmp:
  whaleyeah-sitepackages:

networks:
  whaleyeah-network:
    driver: bridge