net:
  bindIp: 0.0.0.0
  port: 27017
  unixDomainSocket:
    enabled: false

security:
  authorization: disabled

storage:
  dbPath: /data/db
  directoryPerDB: false
  wiredTiger:
    engineConfig:
      cacheSizeGB: 0.5
